-- ============================================================
-- BATCH 2: Semester V
-- ITC501, ITC502, ITC503, ITC504, ITL501, ITL502, ITL503, ITL504,
-- ITL505, ITM501, ITDO5011, ITDO5012, ITDO5013, ITDO5014
-- One test per module, 20 questions each
-- ============================================================
INSERT INTO tests (test_id, test_name, test_description, course_name, course_code, course_semester, course_branch, questions, test_duration, created_at)
VALUES

-- ITC501 - IP | M1: Web Programming Fundamentals
(md5(random()::text),'Web Programming Fundamentals','Module I of Internet Programming: web browser, HTTP, HTTPS, DNS, TLS, XML, JSON, DOM, URL, URI, REST API.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"HTTP stands for:","options_a":"HyperText Transfer Protocol","options_b":"HyperText Transmission Protocol","options_c":"High Transfer Text Protocol","options_d":"None","correct_answer":"option_a"},
{"question":"HTTPS uses:","options_a":"TLS","options_b":"Plain TCP","options_c":"UDP","options_d":"None","correct_answer":"option_a"},
{"question":"DNS resolves:","options_a":"Domain to IP","options_b":"IP to MAC","options_c":"URL to HTML","options_d":"None","correct_answer":"option_a"},
{"question":"TLS provides:","options_a":"Encryption","options_b":"Compression","options_c":"Routing","options_d":"None","correct_answer":"option_a"},
{"question":"XML stands for:","options_a":"eXtensible Markup Language","options_b":"eXtra Markup Language","options_c":"eXternal Markup Language","options_d":"None","correct_answer":"option_a"},
{"question":"JSON stands for:","options_a":"JavaScript Object Notation","options_b":"Java Object Notation","options_c":"JSON Object Notation","options_d":"None","correct_answer":"option_a"},
{"question":"DOM stands for:","options_a":"Document Object Model","options_b":"Data Object Model","options_c":"Direct Object Model","options_d":"None","correct_answer":"option_a"},
{"question":"URL stands for:","options_a":"Uniform Resource Locator","options_b":"Universal Resource Locator","options_c":"Uniform Reference Link","options_d":"None","correct_answer":"option_a"},
{"question":"URI stands for:","options_a":"Uniform Resource Identifier","options_b":"Universal Reference Identifier","options_c":"Uniform Resource Index","options_d":"None","correct_answer":"option_a"},
{"question":"REST stands for:","options_a":"Representational State Transfer","options_b":"Remote State Transfer","options_c":"Reliable State Transfer","options_d":"None","correct_answer":"option_a"},
{"question":"HTTP default port:","options_a":"80","options_b":"443","options_c":"21","options_d":"25","correct_answer":"option_a"},
{"question":"HTTPS default port:","options_a":"443","options_b":"80","options_c":"21","options_d":"25","correct_answer":"option_a"},
{"question":"HTTP method GET:","options_a":"Retrieves data","options_b":"Updates data","options_c":"Deletes data","options_d":"None","correct_answer":"option_a"},
{"question":"HTTP method POST:","options_a":"Submits data","options_b":"Retrieves data","options_c":"Deletes data","options_d":"None","correct_answer":"option_a"},
{"question":"HTTP status 200 means:","options_a":"OK","options_b":"Not Found","options_c":"Server Error","options_d":"None","correct_answer":"option_a"},
{"question":"HTTP status 404 means:","options_a":"Not Found","options_b":"OK","options_c":"Server Error","options_d":"None","correct_answer":"option_a"},
{"question":"HTTP status 500 means:","options_a":"Server Error","options_b":"OK","options_c":"Not Found","options_d":"None","correct_answer":"option_a"},
{"question":"Stateless protocol:","options_a":"HTTP","options_b":"TCP","options_c":"FTP","options_d":"None","correct_answer":"option_a"},
{"question":"DNS uses port:","options_a":"53","options_b":"80","options_c":"443","options_d":"25","correct_answer":"option_a"},
{"question":"REST is:","options_a":"Architectural style","options_b":"Protocol","options_c":"Language","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC501 - IP | M2: JavaScript
(md5(random()::text),'JavaScript','Module II of Internet Programming: ES6, variables, functions, events, arrow functions, DOM manipulation, classes, promises, fetch, async.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"ES6 stands for:","options_a":"ECMAScript 6","options_b":"Extra Script 6","options_c":"E Script 6","options_d":"None","correct_answer":"option_a"},
{"question":"let declares:","options_a":"Block-scoped variable","options_b":"Function-scoped","options_c":"Global","options_d":"None","correct_answer":"option_a"},
{"question":"const declares:","options_a":"Constant","options_b":"Variable","options_c":"Function","options_d":"None","correct_answer":"option_a"},
{"question":"Arrow function syntax:","options_a":"() => {}","options_b":"function() {}","options_c":"=> ()","options_d":"None","correct_answer":"option_a"},
{"question":"DOM manipulation uses:","options_a":"document.querySelector","options_b":"document.get","options_c":"dom.select","options_d":"None","correct_answer":"option_a"},
{"question":"Promise states:","options_a":"pending, fulfilled, rejected","options_b":"only pending","options_c":"only fulfilled","options_d":"None","correct_answer":"option_a"},
{"question":"Async function returns:","options_a":"Promise","options_b":"Value","options_c":"Callback","options_d":"None","correct_answer":"option_a"},
{"question":"Await waits for:","options_a":"Promise","options_b":"Callback","options_c":"Function","options_d":"None","correct_answer":"option_a"},
{"question":"Fetch returns:","options_a":"Promise","options_b":"Value","options_c":"String","options_d":"None","correct_answer":"option_a"},
{"question":"Template literals use:","options_a":"Backticks","options_b":"Quotes","options_c":"Brackets","options_d":"None","correct_answer":"option_a"},
{"question":"Spread operator:","options_a":"...","options_b":"**","options_c":"--","options_d":"None","correct_answer":"option_a"},
{"question":"Destructuring extracts:","options_a":"Values from arrays/objects","options_b":"Classes","options_c":"Functions","options_d":"None","correct_answer":"option_a"},
{"question":"Class keyword:","options_a":"Defines class","options_b":"Defines function","options_c":"Defines var","options_d":"None","correct_answer":"option_a"},
{"question":"Add event listener:","options_a":"addEventListener","options_b":"onEvent","options_c":"listen","options_d":"None","correct_answer":"option_a"},
{"question":"setTimeout:","options_a":"Delays execution","options_b":"Repeats","options_c":"Stops","options_d":"None","correct_answer":"option_a"},
{"question":"setInterval:","options_a":"Repeats execution","options_b":"Delays once","options_c":"Stops","options_d":"None","correct_answer":"option_a"},
{"question":"typeof returns:","options_a":"Data type","options_b":"Value","options_c":"Reference","options_d":"None","correct_answer":"option_a"},
{"question":"JSON.parse converts:","options_a":"String to object","options_b":"Object to string","options_c":"Array to string","options_d":"None","correct_answer":"option_a"},
{"question":"JSON.stringify converts:","options_a":"Object to string","options_b":"String to object","options_c":"Number to string","options_d":"None","correct_answer":"option_a"},
{"question":"== compares:","options_a":"Value","options_b":"Type","options_c":"Reference","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC501 - IP | M3: React Fundamentals
(md5(random()::text),'React Fundamentals','Module III of Internet Programming: components, JSX, props, state, lifecycle, routing, SPA, forms, events, best practices.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"React is:","options_a":"JavaScript library","options_b":"Framework","options_c":"Language","options_d":"None","correct_answer":"option_a"},
{"question":"JSX stands for:","options_a":"JavaScript XML","options_b":"Java Syntax XML","options_c":"JSON XML","options_d":"None","correct_answer":"option_a"},
{"question":"Component is:","options_a":"Reusable UI block","options_b":"Function only","options_c":"Class only","options_d":"None","correct_answer":"option_a"},
{"question":"Props are:","options_a":"Read-only","options_b":"Mutable","options_c":"Global","options_d":"None","correct_answer":"option_a"},
{"question":"State is:","options_a":"Mutable","options_b":"Read-only","options_c":"Constant","options_d":"None","correct_answer":"option_a"},
{"question":"useState returns:","options_a":"[value, setter]","options_b":"[setter, value]","options_c":"value","options_d":"None","correct_answer":"option_a"},
{"question":"useEffect is for:","options_a":"Side effects","options_b":"Styling","options_c":"Routing","options_d":"None","correct_answer":"option_a"},
{"question":"React Router provides:","options_a":"Client-side routing","options_b":"Server routing","options_c":"Styling","options_d":"None","correct_answer":"option_a"},
{"question":"SPA stands for:","options_a":"Single Page Application","options_b":"Simple Page Application","options_c":"Server Page Application","options_d":"None","correct_answer":"option_a"},
{"question":"Keys are used for:","options_a":"List identity","options_b":"Styling","options_c":"Routing","options_d":"None","correct_answer":"option_a"},
{"question":"Virtual DOM:","options_a":"Efficient diffing","options_b":"Real DOM","options_c":"Server","options_d":"None","correct_answer":"option_a"},
{"question":"ReactDOM.render:","options_a":"Mounts component","options_b":"Unmounts","options_c":"Styles","options_d":"None","correct_answer":"option_a"},
{"question":"Functional component:","options_a":"Function returning JSX","options_b":"Class","options_c":"Object","options_d":"None","correct_answer":"option_a"},
{"question":"Class component:","options_a":"Extends React.Component","options_b":"Extends Object","options_c":"Extends Function","options_d":"None","correct_answer":"option_a"},
{"question":"Lifecycle method in class:","options_a":"componentDidMount","options_b":"useEffect","options_c":"onMount","options_d":"None","correct_answer":"option_a"},
{"question":"Controlled component:","options_a":"State controls input","options_b":"DOM controls input","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Uncontrolled uses:","options_a":"Ref","options_b":"State","options_c":"Props","options_d":"None","correct_answer":"option_a"},
{"question":"React vs Angular:","options_a":"Library vs Framework","options_b":"Both frameworks","options_c":"Both libraries","options_d":"None","correct_answer":"option_a"},
{"question":"Props drilling avoided by:","options_a":"Context API","options_b":"useState","options_c":"useEffect","options_d":"None","correct_answer":"option_a"},
{"question":"Bundler used with React:","options_a":"Webpack","options_b":"npm only","options_c":"Node","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC501 - IP | M4: Advanced React
(md5(random()::text),'Advanced React','Module IV of Internet Programming: refs, effects, hooks, MVC, Flux, Webpack.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"useRef returns:","options_a":"Mutable ref object","options_b":"State","options_c":"Props","options_d":"None","correct_answer":"option_a"},
{"question":"Hooks rules:","options_a":"Top-level only","options_b":"Inside loops","options_c":"Inside conditions","options_d":"None","correct_answer":"option_a"},
{"question":"useMemo:","options_a":"Memoizes value","options_b":"Memoizes function","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"useCallback:","options_a":"Memoizes function","options_b":"Memoizes value","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"useContext reads:","options_a":"Context","options_b":"State","options_c":"Props","options_d":"None","correct_answer":"option_a"},
{"question":"Custom hooks start with:","options_a":"use","options_b":"get","options_c":"set","options_d":"None","correct_answer":"option_a"},
{"question":"MVC stands for:","options_a":"Model-View-Controller","options_b":"Model-View-Component","options_c":"Module-View-Controller","options_d":"None","correct_answer":"option_a"},
{"question":"Flux uses:","options_a":"Unidirectional flow","options_b":"Bidirectional","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Redux is:","options_a":"State container","options_b":"Router","options_c":"Bundler","options_d":"None","correct_answer":"option_a"},
{"question":"Webpack is:","options_a":"Bundler","options_b":"Router","options_c":"State","options_d":"None","correct_answer":"option_a"},
{"question":"Babel is:","options_a":"Transpiler","options_b":"Bundler","options_c":"Router","options_d":"None","correct_answer":"option_a"},
{"question":"Code splitting:","options_a":"Loads on demand","options_b":"Loads all","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Lazy loading uses:","options_a":"React.lazy","options_b":"useState","options_c":"useEffect","options_d":"None","correct_answer":"option_a"},
{"question":"Suspense:","options_a":"Fallback UI","options_b":"Error","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Error boundary:","options_a":"Catches errors","options_b":"Throws errors","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Portal renders:","options_a":"Outside DOM hierarchy","options_b":"Inside","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Higher-order component:","options_a":"Function returning component","options_b":"Class","options_c":"Hook","options_d":"None","correct_answer":"option_a"},
{"question":"Render props:","options_a":"Function prop","options_b":"String prop","options_c":"Number prop","options_d":"None","correct_answer":"option_a"},
{"question":"React.memo:","options_a":"Memoizes component","options_b":"State","options_c":"Effect","options_d":"None","correct_answer":"option_a"},
{"question":"SSR stands for:","options_a":"Server-Side Rendering","options_b":"Static Site Render","options_c":"Server Site Render","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC501 - IP | M5: Node.js
(md5(random()::text),'Node.js','Module V of Internet Programming: environment, async, callbacks, event loop, REPL, streams, file system, web module.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"Node.js is:","options_a":"JavaScript runtime","options_b":"Framework","options_c":"Library","options_d":"None","correct_answer":"option_a"},
{"question":"Node.js is:","options_a":"Asynchronous","options_b":"Synchronous","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Event loop:","options_a":"Handles async","options_b":"Handles sync","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Callback:","options_a":"Function passed as arg","options_b":"Promise","options_c":"Async/await","options_d":"None","correct_answer":"option_a"},
{"question":"REPL stands for:","options_a":"Read-Eval-Print-Loop","options_b":"Read-Execute-Print-Loop","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"fs module is:","options_a":"File system","options_b":"Network","options_c":"Crypto","options_d":"None","correct_answer":"option_a"},
{"question":"Streams handle:","options_a":"Data chunks","options_b":"Whole data","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Buffer stores:","options_a":"Binary data","options_b":"Text","options_c":"JSON","options_d":"None","correct_answer":"option_a"},
{"question":"EventEmitter:","options_a":"Emit/listen events","options_b":"Only emit","options_c":"Only listen","options_d":"None","correct_answer":"option_a"},
{"question":"npm is:","options_a":"Package manager","options_b":"Runtime","options_c":"Framework","options_d":"None","correct_answer":"option_a"},
{"question":"package.json:","options_a":"Project metadata","options_b":"Source","options_c":"Binary","options_d":"None","correct_answer":"option_a"},
{"question":"node_modules:","options_a":"Dependencies","options_b":"Source","options_c":"Test","options_d":"None","correct_answer":"option_a"},
{"question":"require() loads:","options_a":"CommonJS","options_b":"ES modules","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"import uses:","options_a":"ES modules","options_b":"CommonJS","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"process.argv:","options_a":"Command-line args","options_b":"Env vars","options_c":"Stdout","options_d":"None","correct_answer":"option_a"},
{"question":"process.env:","options_a":"Env vars","options_b":"Args","options_c":"Stdout","options_d":"None","correct_answer":"option_a"},
{"question":"setImmediate:","options_a":"Defer to next cycle","options_b":"Delay","options_c":"Repeat","options_d":"None","correct_answer":"option_a"},
{"question":"process.nextTick:","options_a":"Defer to next microtask","options_b":"Next cycle","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Cluster module:","options_a":"Multiple workers","options_b":"Single thread","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Worker threads:","options_a":"CPU-intensive","options_b":"I/O","options_c":"Both","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC501 - IP | M6: Express
(md5(random()::text),'Express','Module VI of Internet Programming: Express router, REST API, generator, auth, sessions, integration with React.','Internet Programming','ITC501 - IP','Semester V','Information Technology',
'[
{"question":"Express is:","options_a":"Node.js framework","options_b":"Runtime","options_c":"Library","options_d":"None","correct_answer":"option_a"},
{"question":"Router in Express:","options_a":"Defines routes","options_b":"Middleware only","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Middleware:","options_a":"Functions in pipeline","options_b":"Routes","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"REST API uses:","options_a":"HTTP methods","options_b":"Only GET","options_c":"Only POST","options_d":"None","correct_answer":"option_a"},
{"question":"CRUD:","options_a":"Create Read Update Delete","options_b":"Copy Run Update Delete","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"body-parser:","options_a":"Parses request body","options_b":"Parses response","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"cors:","options_a":"Cross-origin middleware","options_b":"Router","options_c":"Auth","options_d":"None","correct_answer":"option_a"},
{"question":"Sessions use:","options_a":"Cookie","options_b":"LocalStorage","options_c":"SessionStorage","options_d":"None","correct_answer":"option_a"},
{"question":"JWT:","options_a":"Token auth","options_b":"Session","options_c":"Cookie","options_d":"None","correct_answer":"option_a"},
{"question":"bcrypt:","options_a":"Password hashing","options_b":"Encryption","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Mongoose:","options_a":"MongoDB ODM","options_b":"SQL ORM","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Axios:","options_a":"HTTP client","options_b":"Server","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CORS stands for:","options_a":"Cross-Origin Resource Sharing","options_b":"Central Origin Resource","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Express generator:","options_a":"Scaffolding","options_b":"Bundler","options_c":"Router","options_d":"None","correct_answer":"option_a"},
{"question":"Error middleware:","options_a":"4 params","options_b":"2 params","options_c":"3 params","options_d":"None","correct_answer":"option_a"},
{"question":"Static files:","options_a":"express.static","options_b":"express.files","options_c":"express.dir","options_d":"None","correct_answer":"option_a"},
{"question":"Route params:","options_a":":id","options_b":"?id","options_c":"#id","options_d":"None","correct_answer":"option_a"},
{"question":"Query params:","options_a":"req.query","options_b":"req.body","options_c":"req.params","options_d":"None","correct_answer":"option_a"},
{"question":"Body:","options_a":"req.body","options_b":"req.query","options_c":"req.params","options_d":"None","correct_answer":"option_a"},
{"question":"Route params:","options_a":"req.params","options_b":"req.body","options_c":"req.query","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC502 - CNS | M1: Network Security & Cryptography
(md5(random()::text),'Introduction to Network Security','Module I of Computer Network Security: CIA, services, mechanisms, attacks, OSI security architecture, classical encryption.','Computer Network Security','ITC502 - CNS','Semester V','Information Technology',
'[
{"question":"CIA stands for:","options_a":"Confidentiality, Integrity, Availability","options_b":"Central Intelligence Agency","options_c":"Cryptography Integrity Access","options_d":"None","correct_answer":"option_a"},
{"question":"Confidentiality:","options_a":"Prevent unauthorized disclosure","options_b":"Prevent alteration","options_c":"Ensure availability","options_d":"None","correct_answer":"option_a"},
{"question":"Integrity:","options_a":"Prevent unauthorized modification","options_b":"Prevent disclosure","options_c":"Ensure availability","options_d":"None","correct_answer":"option_a"},
{"question":"Availability:","options_a":"Ensure timely access","options_b":"Encryption","options_c":"Integrity","options_d":"None","correct_answer":"option_a"},
{"question":"OSI security architecture has:","options_a":"Security services and mechanisms","options_b":"Only services","options_c":"Only mechanisms","options_d":"None","correct_answer":"option_a"},
{"question":"Passive attack:","options_a":"Eavesdropping","options_b":"Modification","options_c":"Denial","options_d":"None","correct_answer":"option_a"},
{"question":"Active attack:","options_a":"Modification","options_b":"Eavesdropping","options_c":"Interception","options_d":"None","correct_answer":"option_a"},
{"question":"Caesar cipher is:","options_a":"Substitution","options_b":"Transposition","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Vigenere cipher is:","options_a":"Poly-alphabetic","options_b":"Mono-alphabetic","options_c":"Transposition","options_d":"None","correct_answer":"option_a"},
{"question":"Playfair cipher uses:","options_a":"5x5 matrix","options_b":"4x4 matrix","options_c":"3x3 matrix","options_d":"None","correct_answer":"option_a"},
{"question":"Transposition cipher:","options_a":"Rearranges letters","options_b":"Substitutes letters","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Steganography:","options_a":"Hides existence","options_b":"Encrypts","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Cryptanalysis:","options_a":"Breaking ciphers","options_b":"Creating ciphers","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Brute force attack:","options_a":"Tries all keys","options_b":"Single key","options_c":"No key","options_d":"None","correct_answer":"option_a"},
{"question":"Kerckhoff''s principle:","options_a":"Security depends on key","options_b":"Algorithm","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Symmetric key:","options_a":"Same key","options_b":"Different keys","options_c":"Public key","options_d":"None","correct_answer":"option_a"},
{"question":"Asymmetric:","options_a":"Public and private keys","options_b":"Same key","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Authentication:","options_a":"Verifies identity","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Non-repudiation:","options_a":"Cannot deny action","options_b":"Hide data","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Access control:","options_a":"Restricts access","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC502 - CNS | M2: Key Management and Authentication
(md5(random()::text),'Cryptography: Key Management and Authentication','Module II of Computer Network Security: block cipher modes, DES, AES, RSA, hashing, HMAC, digital signatures, Kerberos, PKI.','Computer Network Security','ITC502 - CNS','Semester V','Information Technology',
'[
{"question":"DES key size:","options_a":"56 bits","options_b":"128","options_c":"192","options_d":"256","correct_answer":"option_a"},
{"question":"AES key sizes:","options_a":"128, 192, 256","options_b":"56","options_c":"64","options_d":"512","correct_answer":"option_a"},
{"question":"Block cipher mode ECB:","options_a":"Electronic Codebook","options_b":"Encrypted Code Book","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CBC uses:","options_a":"IV","options_b":"No IV","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"RSA based on:","options_a":"Prime factorization","options_b":"Discrete log","options_c":"Elliptic curves","options_d":"None","correct_answer":"option_a"},
{"question":"RSA key size recommended:","options_a":"2048+","options_b":"512","options_c":"128","options_d":"256","correct_answer":"option_a"},
{"question":"SHA-256 produces:","options_a":"256-bit hash","options_b":"128-bit","options_c":"512-bit","options_d":"64-bit","correct_answer":"option_a"},
{"question":"HMAC:","options_a":"Keyed hash","options_b":"Unkeyed","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Digital signature uses:","options_a":"Private key to sign","options_b":"Public key to sign","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Digital signature verified by:","options_a":"Public key","options_b":"Private key","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"X.509:","options_a":"Digital certificate","options_b":"Protocol","options_c":"Algorithm","options_d":"None","correct_answer":"option_a"},
{"question":"PKI stands for:","options_a":"Public Key Infrastructure","options_b":"Private Key Infrastructure","options_c":"Public Key Interface","options_d":"None","correct_answer":"option_a"},
{"question":"CA stands for:","options_a":"Certificate Authority","options_b":"Certificate Access","options_c":"Central Authority","options_d":"None","correct_answer":"option_a"},
{"question":"Kerberos uses:","options_a":"Tickets","options_b":"Cookies","options_c":"Tokens","options_d":"None","correct_answer":"option_a"},
{"question":"Kerberos relies on:","options_a":"Symmetric key","options_b":"Asymmetric","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Diffie-Hellman:","options_a":"Key exchange","options_b":"Encryption","options_c":"Hashing","options_d":"None","correct_answer":"option_a"},
{"question":"Elliptic curve:","options_a":"Smaller keys","options_b":"Larger keys","options_c":"Same","options_d":"None","correct_answer":"option_a"},
{"question":"MD5 produces:","options_a":"128-bit hash","options_b":"256","options_c":"512","options_d":"64","correct_answer":"option_a"},
{"question":"Collision resistance:","options_a":"Hard to find two inputs","options_b":"Easy","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CMAC:","options_a":"Cipher-based MAC","options_b":"Hash-based","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC502 - CNS | M3: Malicious Software
(md5(random()::text),'Malicious Software','Module III of Computer Network Security: viruses, worms, trojans, rootkits, phishing, DoS.','Computer Network Security','ITC502 - CNS','Semester V','Information Technology',
'[
{"question":"Virus:","options_a":"Needs host","options_b":"Self-replicating","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Worm:","options_a":"Self-replicating","options_b":"Needs host","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Trojan:","options_a":"Disguised as useful","options_b":"Self-replicating","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Rootkit:","options_a":"Hides presence","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Phishing:","options_a":"Social engineering","options_b":"Hashing","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"DoS:","options_a":"Denial of Service","options_b":"Data over Service","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"DDoS:","options_a":"Distributed DoS","options_b":"Direct DoS","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Zombie:","options_a":"Compromised host","options_b":"Firewall","options_c":"Router","options_d":"None","correct_answer":"option_a"},
{"question":"Botnet:","options_a":"Network of bots","options_b":"Single bot","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Backdoor:","options_a":"Hidden access","options_b":"Firewall","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Trapdoor:","options_a":"Secret entry point","options_b":"Firewall","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Logic bomb:","options_a":"Triggers on condition","options_b":"Random","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Keylogger:","options_a":"Records keystrokes","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Spyware:","options_a":"Collects info","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Adware:","options_a":"Shows ads","options_b":"Encrypts","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Ransomware:","options_a":"Demands payment","options_b":"Free","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Malware:","options_a":"Malicious software","options_b":"Good software","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Antivirus:","options_a":"Detects malware","options_b":"Creates malware","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Signature-based detection:","options_a":"Matches known patterns","options_b":"Behavior","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Behavior-based:","options_a":"Detects anomalies","options_b":"Signatures","options_c":"Both","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC502 - CNS | M4: IP Security, Transport and Email Security
(md5(random()::text),'IP Security, Transport and Email Security','Module IV of Computer Network Security: IPSec, AH, ESP, SSL/TLS, HTTPS, SSH, S/MIME.','Computer Network Security','ITC502 - CNS','Semester V','Information Technology',
'[
{"question":"IPSec operates at:","options_a":"Network layer","options_b":"Transport","options_c":"Application","options_d":"None","correct_answer":"option_a"},
{"question":"AH provides:","options_a":"Authentication","options_b":"Confidentiality","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"ESP provides:","options_a":"Confidentiality+auth","options_b":"Only auth","options_c":"Only encryption","options_d":"None","correct_answer":"option_a"},
{"question":"IPSec modes:","options_a":"Transport and tunnel","options_b":"Only transport","options_c":"Only tunnel","options_d":"None","correct_answer":"option_a"},
{"question":"IKE:","options_a":"Key exchange","options_b":"Encryption","options_c":"Hashing","options_d":"None","correct_answer":"option_a"},
{"question":"SSL/TLS at:","options_a":"Transport","options_b":"Network","options_c":"Application","options_d":"None","correct_answer":"option_a"},
{"question":"TLS handshake:","options_a":"Negotiates crypto","options_b":"Encrypts data","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"HTTPS uses:","options_a":"TLS","options_b":"Plain TCP","options_c":"UDP","options_d":"None","correct_answer":"option_a"},
{"question":"SSH provides:","options_a":"Secure remote login","options_b":"Unsecure","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"SSH port:","options_a":"22","options_b":"23","options_c":"80","options_d":"443","correct_answer":"option_a"},
{"question":"TELNET port:","options_a":"23","options_b":"22","options_c":"80","options_d":"443","correct_answer":"option_a"},
{"question":"VPN:","options_a":"Virtual Private Network","options_b":"Very Private Network","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"S/MIME:","options_a":"Email security","options_b":"Web security","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"PGP:","options_a":"Email encryption","options_b":"Web","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Email uses:","options_a":"SMTP, POP3, IMAP","options_b":"HTTP only","options_c":"FTP","options_d":"None","correct_answer":"option_a"},
{"question":"PGP uses:","options_a":"Hybrid crypto","options_b":"Only symmetric","options_c":"Only asymmetric","options_d":"None","correct_answer":"option_a"},
{"question":"S/MIME uses:","options_a":"X.509","options_b":"PGP keys","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"TLS record:","options_a":"Encrypts data","options_b":"Handshake","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Perfect forward secrecy:","options_a":"Ephemeral keys","options_b":"Static keys","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"HTTPS port:","options_a":"443","options_b":"80","options_c":"22","options_d":"25","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC502 - CNS | M5: Network Management Security and NAC
(md5(random()::text),'Network Management Security and NAC','Module V of Computer Network Security: SNMPv3, NAC elements, enforcement methods, and use cases.','Computer Network Security','ITC502 - CNS','Semester V','Information Technology',
'[
{"question":"SNMP stands for:","options_a":"Simple Network Management Protocol","options_b":"Standard Network Mgmt Protocol","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SNMPv3 adds:","options_a":"Security","options_b":"Speed","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SNMP uses:","options_a":"UDP","options_b":"TCP","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"MIB:","options_a":"Management Info Base","options_b":"Memory Info Base","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"NAC stands for:","options_a":"Network Access Control","options_b":"Network Access Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"NAC enforces:","options_a":"Policy on devices","options_b":"Firewall","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"NAC elements:","options_a":"Agent, server, policy","options_b":"Only server","options_c":"Only agent","options_d":"None","correct_answer":"option_a"},
{"question":"802.1X:","options_a":"Port-based NAC","options_b":"Routing","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"RADIUS:","options_a":"AAA protocol","options_b":"Routing","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"TACACS+:","options_a":"AAA protocol","options_b":"Routing","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Pre-admission NAC:","options_a":"Before access","options_b":"After","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Post-admission NAC:","options_a":"After access","options_b":"Before","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Agent-based NAC:","options_a":"Software on device","options_b":"Network-based","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Agentless NAC:","options_a":"Network-based","options_b":"Software","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"NAC use cases:","options_a":"BYOD, guest","options_b":"Routing","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SNMP traps:","options_a":"Alerts","options_b":"Queries","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"MIB is:","options_a":"Hierarchical DB","options_b":"Flat","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SNMP manager:","options_a":"Queries agents","options_b":"Only responds","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"SNMP agent:","options_a":"Responds to manager","options_b":"Only queries","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"NAC goals:","options_a":"Compliance","options_b":"Speed","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC503 - EEB | M1: Introduction
(md5(random()::text),'Introduction to Entrepreneurship','Module I of Entrepreneurship and E-business: entrepreneur, evolution, types, women, corporate and social entrepreneurship.','Entrepreneurship and E-business','ITC503 - EEB','Semester V','Information Technology',
'[
{"question":"Entrepreneur:","options_a":"Starts a business","options_b":"Employee","options_c":"Investor","options_d":"None","correct_answer":"option_a"},
{"question":"Entrepreneurship involves:","options_a":"Risk and innovation","options_b":"Only risk","options_c":"Only innovation","options_d":"None","correct_answer":"option_a"},
{"question":"Intrapreneur:","options_a":"Entrepreneur within company","options_b":"Outside","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Types of entrepreneurs:","options_a":"Innovative, imitative","options_b":"Only innovative","options_c":"Only imitative","options_d":"None","correct_answer":"option_a"},
{"question":"Women entrepreneurs:","options_a":"Women owning businesses","options_b":"Men","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Social entrepreneurship:","options_a":"Social mission","options_b":"Profit only","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Corporate entrepreneurship:","options_a":"Within corporation","options_b":"Outside","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Role of entrepreneurship:","options_a":"Economic development","options_b":"Only employment","options_c":"Only innovation","options_d":"None","correct_answer":"option_a"},
{"question":"Managerial vs entrepreneurial:","options_a":"Resource vs opportunity","options_b":"Same","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Startup:","options_a":"New venture","options_b":"Mature","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Risk-taking:","options_a":"Accepting uncertainty","options_b":"Avoiding","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Innovation:","options_a":"New ideas","options_b":"Old ideas","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Business plan:","options_a":"Document","options_b":"Idea","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Vision:","options_a":"Future goal","options_b":"Past","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Mission:","options_a":"Purpose","options_b":"Vision","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Small business:","options_a":"SME","options_b":"MNC","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Franchise:","options_a":"Business model","options_b":"Product","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Angel investor:","options_a":"Early-stage investor","options_b":"Late investor","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"VC:","options_a":"Venture Capital","options_b":"Very Capital","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Exit strategy:","options_a":"Sale or IPO","options_b":"None","options_c":"Random","options_d":"All of the above","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC503 - EEB | M2: Leadership and Development
(md5(random()::text),'Entrepreneurship Development and Leadership','Module II of Entrepreneurship and E-business: motivation, startup types, ownership structures, SMEs.','Entrepreneurship and E-business','ITC503 - EEB','Semester V','Information Technology',
'[
{"question":"Motivation factors:","options_a":"Achievement, power, affiliation","options_b":"Only profit","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Startup types:","options_a":"Scalable, small business","options_b":"Only scalable","options_c":"Only small","options_d":"None","correct_answer":"option_a"},
{"question":"Entrepreneurial leadership:","options_a":"Vision, risk, innovation","options_b":"Only vision","options_c":"Only risk","options_d":"None","correct_answer":"option_a"},
{"question":"Ownership types:","options_a":"Sole, partnership, company","options_b":"Only sole","options_c":"Only company","options_d":"None","correct_answer":"option_a"},
{"question":"Sole proprietorship:","options_a":"One owner","options_b":"Two","options_c":"Many","options_d":"None","correct_answer":"option_a"},
{"question":"Partnership:","options_a":"Two or more","options_b":"One","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"LLP:","options_a":"Limited Liability Partnership","options_b":"Limited Long Partnership","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Pvt Ltd:","options_a":"Private Limited","options_b":"Public","options_c":"Partnership","options_d":"None","correct_answer":"option_a"},
{"question":"SME:","options_a":"Small Medium Enterprise","options_b":"Small Management Entity","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"MSME:","options_a":"Micro Small Medium Enterprise","options_b":"Micro Small","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Capital structure:","options_a":"Debt+equity","options_b":"Only debt","options_c":"Only equity","options_d":"None","correct_answer":"option_a"},
{"question":"Bootstrapping:","options_a":"Self-funding","options_b":"VC","options_c":"Loan","options_d":"None","correct_answer":"option_a"},
{"question":"Crowdfunding:","options_a":"Public funding","options_b":"VC","options_c":"Bank","options_d":"None","correct_answer":"option_a"},
{"question":"Incubator:","options_a":"Startup support","options_b":"Bank","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Accelerator:","options_a":"Fast-track support","options_b":"Bank","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Pitch deck:","options_a":"Presentation","options_b":"Contract","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"MVP:","options_a":"Minimum Viable Product","options_b":"Most Valuable Product","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Lean startup:","options_a":"Build-measure-learn","options_b":"Waterfall","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Pivot:","options_a":"Change direction","options_b":"Stop","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Scalability:","options_a":"Growth capacity","options_b":"Shrink","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC503 - EEB | M3: New Venture Planning
(md5(random()::text),'New Venture Planning','Module III of Entrepreneurship and E-business: methods, acquisition, marketing plan, business plan.','Entrepreneurship and E-business','ITC503 - EEB','Semester V','Information Technology',
'[
{"question":"Venture initiation methods:","options_a":"Start, buy, franchise","options_b":"Only start","options_c":"Only buy","options_d":"None","correct_answer":"option_a"},
{"question":"Acquisition:","options_a":"Buying existing venture","options_b":"Starting","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Franchise:","options_a":"Licensed model","options_b":"Start","options_c":"Buy","options_d":"None","correct_answer":"option_a"},
{"question":"Business plan:","options_a":"Written document","options_b":"Idea","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Marketing plan:","options_a":"Customer+competition","options_b":"Only customer","options_c":"Only competition","options_d":"None","correct_answer":"option_a"},
{"question":"Target market:","options_a":"Chosen segment","options_b":"All","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Value proposition:","options_a":"Benefit offered","options_b":"Price","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Revenue model:","options_a":"How you earn","options_b":"How you spend","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Cost structure:","options_a":"Fixed+variable","options_b":"Only fixed","options_c":"Only variable","options_d":"None","correct_answer":"option_a"},
{"question":"Break-even:","options_a":"No profit no loss","options_b":"Profit","options_c":"Loss","options_d":"None","correct_answer":"option_a"},
{"question":"SWOT:","options_a":"Strengths Weaknesses Opportunities Threats","options_b":"Only S","options_c":"Only W","options_d":"None","correct_answer":"option_a"},
{"question":"Competitor analysis:","options_a":"Study rivals","options_b":"Study customers","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Market research:","options_a":"Collect data","options_b":"Guess","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Primary research:","options_a":"Direct data","options_b":"Published","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Secondary research:","options_a":"Published data","options_b":"Direct","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Elevator pitch:","options_a":"Short pitch","options_b":"Long","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Milestones:","options_a":"Key events","options_b":"None","options_c":"Random","options_d":"All","correct_answer":"option_a"},
{"question":"Financials in plan:","options_a":"Projections","options_b":"None","options_c":"Random","options_d":"All","correct_answer":"option_a"},
{"question":"Risk analysis:","options_a":"Identify risks","options_b":"Ignore","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Exit plan:","options_a":"IPO or sale","options_b":"None","options_c":"Random","options_d":"All","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC503 - EEB | M4: Financing and Managing Venture
(md5(random()::text),'Financing and Managing Venture','Module IV of Entrepreneurship and E-business: financing stages, sources, VC, HRM.','Entrepreneurship and E-business','ITC503 - EEB','Semester V','Information Technology',
'[
{"question":"Financing stages:","options_a":"Seed, early, growth","options_b":"Only seed","options_c":"Only growth","options_d":"None","correct_answer":"option_a"},
{"question":"Seed funding:","options_a":"Initial","options_b":"Later","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Series A:","options_a":"Early VC","options_b":"Late","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Sources of finance:","options_a":"Equity, debt, hybrid","options_b":"Only equity","options_c":"Only debt","options_d":"None","correct_answer":"option_a"},
{"question":"VC:","options_a":"Venture Capital","options_b":"Very Capital","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Angel:","options_a":"Early investor","options_b":"Late","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Bank loan:","options_a":"Debt","options_b":"Equity","options_c":"Hybrid","options_d":"None","correct_answer":"option_a"},
{"question":"Convertible note:","options_a":"Hybrid","options_b":"Debt","options_c":"Equity","options_d":"None","correct_answer":"option_a"},
{"question":"Term sheet:","options_a":"Investment terms","options_b":"Contract","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Valuation:","options_a":"Company worth","options_b":"Price","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Dilution:","options_a":"Ownership reduction","options_b":"Increase","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Cap table:","options_a":"Ownership table","options_b":"Cost","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Management functions:","options_a":"Plan, organize, lead, control","options_b":"Only plan","options_c":"Only control","options_d":"None","correct_answer":"option_a"},
{"question":"Scientific management:","options_a":"Taylor","options_b":"Fayol","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Strategic management:","options_a":"Long-term","options_b":"Short-term","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"HRM:","options_a":"Human Resource Management","options_b":"HR","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Recruitment:","options_a":"Hiring","options_b":"Firing","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Training:","options_a":"Skill development","options_b":"Hiring","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Job analysis:","options_a":"Role description","options_b":"Hiring","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Compensation:","options_a":"Pay+benefits","options_b":"Only pay","options_c":"Only benefits","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M1: Introduction to Software Engineering
(md5(random()::text),'Introduction to Software Engineering','Module I of Software Engineering: nature of software, process, CMM, process models (waterfall, V, incremental, evolutionary, agile, scrum, kanban).','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"Software engineering:","options_a":"Discipline for software development","options_b":"Only coding","options_c":"Only testing","options_d":"None","correct_answer":"option_a"},
{"question":"Software process:","options_a":"Set of activities","options_b":"Only coding","options_c":"Only testing","options_d":"None","correct_answer":"option_a"},
{"question":"CMM:","options_a":"Capability Maturity Model","options_b":"Code Maturity Model","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CMM levels:","options_a":"5","options_b":"3","options_c":"4","options_d":"6","correct_answer":"option_a"},
{"question":"Waterfall:","options_a":"Sequential","options_b":"Iterative","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"V-model:","options_a":"Verification+validation","options_b":"Only verification","options_c":"Only validation","options_d":"None","correct_answer":"option_a"},
{"question":"Incremental:","options_a":"Deliver increments","options_b":"One delivery","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Evolutionary:","options_a":"Iterative evolution","options_b":"One shot","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Concurrent:","options_a":"Parallel activities","options_b":"Sequential","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Agile:","options_a":"Iterative and incremental","options_b":"Waterfall","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Agile principles:","options_a":"12","options_b":"5","options_c":"4","options_d":"10","correct_answer":"option_a"},
{"question":"XP stands for:","options_a":"Extreme Programming","options_b":"X Programming","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Scrum roles:","options_a":"PO, SM, dev team","options_b":"Only PO","options_c":"Only SM","options_d":"None","correct_answer":"option_a"},
{"question":"Sprint:","options_a":"Time-boxed iteration","options_b":"Release","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Kanban:","options_a":"Visual workflow","options_b":"Waterfall","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"WIP limit:","options_a":"Kanban constraint","options_b":"Sprint goal","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Backlog:","options_a":"Pending work","options_b":"Done work","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Daily scrum:","options_a":"15 min standup","options_b":"Hourly","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Retrospective:","options_a":"End-of-sprint review","options_b":"Start","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CMMI:","options_a":"CMM Integration","options_b":"CMM Initial","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M2: Requirement Analysis
(md5(random()::text),'Requirement Analysis','Module II of Software Engineering: functional and non-functional requirements, elicitation, SRS, prototyping, modeling.','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"Functional requirement:","options_a":"Behavior","options_b":"Performance","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Non-functional:","options_a":"Quality attribute","options_b":"Behavior","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Requirement engineering:","options_a":"Elicit, analyze, specify","options_b":"Only elicit","options_c":"Only specify","options_d":"None","correct_answer":"option_a"},
{"question":"Feasibility study:","options_a":"Is project viable","options_b":"Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Elicitation:","options_a":"Gather requirements","options_b":"Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SRS stands for:","options_a":"Software Requirements Specification","options_b":"System Requirements Spec","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SRS purpose:","options_a":"Document requirements","options_b":"Code","options_c":"Test","options_d":"None","correct_answer":"option_a"},
{"question":"Prototyping:","options_a":"Early model","options_b":"Final product","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Use case:","options_a":"Interaction scenario","options_b":"Code","options_c":"Test","options_d":"None","correct_answer":"option_a"},
{"question":"Actor:","options_a":"External entity","options_b":"Internal","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Kano model:","options_a":"Prioritizing requirements","options_b":"Coding","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Requirement validation:","options_a":"Check correctness","options_b":"Gather","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Traceability:","options_a":"Link requirements","options_b":"Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Analysis model:","options_a":"Conceptual","options_b":"Code","options_c":"Test","options_d":"None","correct_answer":"option_a"},
{"question":"DFD:","options_a":"Data Flow Diagram","options_b":"Data Format Diagram","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"ER diagram:","options_a":"Entity Relationship","options_b":"Error Report","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Class diagram:","options_a":"UML","options_b":"DFD","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Sequence diagram:","options_a":"UML","options_b":"DFD","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"User story:","options_a":"Short requirement","options_b":"Long doc","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Requirement prioritization:","options_a":"Rank","options_b":"Gather","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M3: Estimation and Scheduling
(md5(random()::text),'Software Estimation and Scheduling','Module III of Software Engineering: LOC, FP, COCOMO II, project scheduling, timeline, earned value.','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"LOC:","options_a":"Lines of Code","options_b":"Level of Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"FP:","options_a":"Function Points","options_b":"Fast Points","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"COCOMO:","options_a":"Estimation model","options_b":"Coding","options_c":"Testing","options_d":"None","correct_answer":"option_a"},
{"question":"Organic mode:","options_a":"Small team","options_b":"Large team","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Semi-detached:","options_a":"Medium","options_b":"Small","options_c":"Large","options_d":"None","correct_answer":"option_a"},
{"question":"Embedded:","options_a":"Complex","options_b":"Simple","options_c":"Medium","options_d":"None","correct_answer":"option_a"},
{"question":"Effort formula:","options_a":"a(KLOC)^b","options_b":"a*LOC","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"PERT:","options_a":"Program Eval Review Technique","options_b":"Program Estimate Review","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CPM:","options_a":"Critical Path Method","options_b":"Cost Per Module","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Gantt chart:","options_a":"Schedule","options_b":"Cost","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"WBS:","options_a":"Work Breakdown Structure","options_b":"Work Basic Schedule","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Milestone:","options_a":"Key event","options_b":"Task","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Critical path:","options_a":"Longest path","options_b":"Shortest","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Slack:","options_a":"Float","options_b":"Delay","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Earned value:","options_a":"Progress measure","options_b":"Cost","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SPI:","options_a":"Schedule Perf Index","options_b":"Cost","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"CPI:","options_a":"Cost Perf Index","options_b":"Schedule","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Timeline chart:","options_a":"Schedule","options_b":"Cost","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"3Ps:","options_a":"People, product, process","options_b":"Plan, perform","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Effort vs schedule:","options_a":"Nonlinear","options_b":"Linear","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M4: Design Engineering
(md5(random()::text),'Design Engineering','Module IV of Software Engineering: design concepts, architecture, component-level, UI design.','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"Design concepts:","options_a":"Abstraction, modularity","options_b":"Only abstraction","options_c":"Only modularity","options_d":"None","correct_answer":"option_a"},
{"question":"Modularity:","options_a":"Divide and conquer","options_b":"Monolith","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Cohesion:","options_a":"Within module","options_b":"Between modules","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Coupling:","options_a":"Between modules","options_b":"Within module","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"High cohesion:","options_a":"Good","options_b":"Bad","options_c":"Neutral","options_d":"None","correct_answer":"option_a"},
{"question":"Low coupling:","options_a":"Good","options_b":"Bad","options_c":"Neutral","options_d":"None","correct_answer":"option_a"},
{"question":"Architectural design:","options_a":"High level","options_b":"Low level","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Layered architecture:","options_a":"Layers","options_b":"Monolith","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"MVC:","options_a":"Model-View-Controller","options_b":"Module","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Component-level:","options_a":"Class design","options_b":"Architecture","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"UI golden rules:","options_a":"Consistency, feedback","options_b":"Only consistency","options_c":"Only feedback","options_d":"None","correct_answer":"option_a"},
{"question":"Interface design steps:","options_a":"Analysis, design, evaluation","options_b":"Only design","options_c":"Only analysis","options_d":"None","correct_answer":"option_a"},
{"question":"Design patterns:","options_a":"Reusable solutions","options_b":"Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Singleton:","options_a":"One instance","options_b":"Many","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Factory:","options_a":"Object creation","options_b":"Destruction","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Observer:","options_a":"Notify changes","options_b":"Observe","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Design evaluation:","options_a":"Review metrics","options_b":"Code","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Refactoring:","options_a":"Improve structure","options_b":"Add features","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Aspect:","options_a":"Cross-cutting","options_b":"Module","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Design model:","options_a":"Data, architecture, interface","options_b":"Only data","options_c":"Only architecture","options_d":"None","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M5: Risk and Configuration Management
(md5(random()::text),'Software Risk and Configuration Management','Module V of Software Engineering: risk identification, RMMM, SCM, QA, FTR.','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"Risk:","options_a":"Potential problem","options_b":"Certain problem","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Risk identification:","options_a":"Find risks","options_b":"Solve","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Risk projection:","options_a":"Estimate impact","options_b":"Solve","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"RMMM:","options_a":"Risk Mitigation, Monitoring, Mgmt","options_b":"Risk Model","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Risk assessment:","options_a":"Evaluate risks","options_b":"Solve","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"SCM:","options_a":"Software Configuration Management","options_b":"Source Code Mgmt","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Configuration item:","options_a":"Work product","options_b":"Code only","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Baseline:","options_a":"Approved version","options_b":"Draft","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Version control:","options_a":"Track changes","options_b":"Delete","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Git is:","options_a":"VCS","options_b":"Editor","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Change control:","options_a":"Manage changes","options_b":"Freeze","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"SQA:","options_a":"Software Quality Assurance","options_b":"QA only","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"FTR:","options_a":"Formal Technical Review","options_b":"Fast Tech Review","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Walkthrough:","options_a":"Informal review","options_b":"Formal","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Inspection:","options_a":"Formal review","options_b":"Informal","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Metrics:","options_a":"Measure","options_b":"None","options_c":"Random","options_d":"All","correct_answer":"option_a"},
{"question":"Reliability:","options_a":"Probability of failure-free","options_b":"Failure","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"MTTF:","options_a":"Mean Time To Failure","options_b":"Time To Fix","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"MTTR:","options_a":"Mean Time To Repair","options_b":"Time To Fail","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Availability:","options_a":"MTTF/(MTTF+MTTR)","options_b":"MTTR/(MTTF)","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Defect density:","options_a":"Defects/KLOC","options_b":"KLOC","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW()),

-- ITC504 - SE | M6: Testing and Maintenance
(md5(random()::text),'Software Testing and Maintenance','Module VI of Software Engineering: testing strategies, debugging, maintenance, reengineering.','Software Engineering','ITC504 - SE','Semester V','Information Technology',
'[
{"question":"Testing goal:","options_a":"Find defects","options_b":"Prove correct","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Unit testing:","options_a":"Single unit","options_b":"Whole","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Integration testing:","options_a":"Module interaction","options_b":"Single module","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"System testing:","options_a":"Whole system","options_b":"Module","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Acceptance testing:","options_a":"User validation","options_b":"Unit","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Black box:","options_a":"No internal knowledge","options_b":"Internal knowledge","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"White box:","options_a":"Internal knowledge","options_b":"No knowledge","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Boundary value:","options_a":"Test edges","options_b":"Middle","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Equivalence class:","options_a":"Group inputs","options_b":"Random","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Basis path:","options_a":"Cyclomatic complexity","options_b":"Random","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Cyclomatic complexity:","options_a":"E-N+2","options_b":"E+N","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Regression testing:","options_a":"Re-run tests","options_b":"New tests","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Debugging:","options_a":"Locate and fix","options_b":"Test","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Maintenance types:","options_a":"Corrective, adaptive, perfective, preventive","options_b":"Only corrective","options_c":"Only adaptive","options_d":"None","correct_answer":"option_a"},
{"question":"Corrective:","options_a":"Fix bugs","options_b":"New features","options_c":"Adapt","options_d":"None","correct_answer":"option_a"},
{"question":"Adaptive:","options_a":"Environment change","options_b":"Fix bugs","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Perfective:","options_a":"Improve","options_b":"Fix","options_c":"Adapt","options_d":"None","correct_answer":"option_a"},
{"question":"Preventive:","options_a":"Prevent future issues","options_b":"Fix now","options_c":"None","options_d":"Random","correct_answer":"option_a"},
{"question":"Reengineering:","options_a":"Restructure","options_b":"Rewrite","options_c":"Both","options_d":"None","correct_answer":"option_a"},
{"question":"Reverse engineering:","options_a":"Recover design","options_b":"Forward","options_c":"None","options_d":"Random","correct_answer":"option_a"}
]'::jsonb,'20',NOW());